name: wasteagram
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  location: ^4.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.19.5

flutter:

  uses-material-design: true
